services:
  - type: web
    name: journita-travel-agent
    runtime: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile.gcp
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: SERPAPI_API_KEY
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /health
    buildCommand: ""
    startCommand: ""
